parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'

ignorePatterns:
  - 'dist'
  - 'cypress.base.config.ts'
  - 'cypress.regression.config.ts'
  - 'cypress.common.config.ts'
  - 'cypress'
  - 'src/utils/*.spec.ts'
  - 'tests'

plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'import'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'standard-with-typescript'
  - 'plugin:promise/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'

settings:
  import/resolver:
    typescript: true
    node: true

rules:
  '@typescript-eslint/ban-ts-comment': 'warn'
  '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  '@typescript-eslint/no-explicit-any': 'warn'
  '@typescript-eslint/no-invalid-void-type': 'off'
  '@typescript-eslint/restrict-template-expressions': 'off'
  'no-param-reassign': 'error'
