name: Continuous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        cypress-version: [12.x, 13.x]
        project-setup: [esm, cjs, ts, ts-alt]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci
          npm run build
          npm install cypress@${{ matrix.cypress-version }}

      - name: Run cypress tests
        run: npm run cy:base-and-regression

      - name: Run plugin on ${{ matrix.project-setup }} project setup
        run: |
          cd ./tests/${{ matrix.project-setup }}
          npm ci
          npm run test
